services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: mealplanner-postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mealplanner
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "9090:80"
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.de
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
     - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    ports:
      - "9000:8080"
    container_name: mealplanner_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./local-infrastructure/keycloak-setup.sh:/opt/keycloak/keycloak-setup.sh
    entrypoint: ["/bin/sh", "-c", "/opt/keycloak/keycloak-setup.sh & /opt/keycloak/bin/kc.sh start-dev"]

volumes:
  postgres-data:
  pgadmin-data:
  keycloak-data:
